# Generated by Django 4.1.5 on 2024-07-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, db_column="USER_NAME", max_length=150, null=True
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, db_column="PASSWORD", max_length=150, null=True
                    ),
                ),
            ],
        ),
    ]
