# Generated by Django 4.1.5 on 2024-07-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainlogin", "0002_login_f_name_login_l_name_login_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="login",
            name="approval",
            field=models.CharField(
                blank=True, db_column="APPROVAL", max_length=150, null=True
            ),
        ),
    ]
